### ISSUE TITLE
Error: Invalid object name 'npo02__Household__r'

### ISSUE THREAD

**Issue by tkcharles12** [davidhabib/Auctions-for-Salesforce#129]
When navigating to the Auction Receipts tab, the following error appears before anything else is selected: Invalid object name 'npo02__Household__r'
![A4S Error](https://user-images.githubusercontent.com/49493282/55900009-0c7af300-5b7b-11e9-988a-fc86ffa1a8fc.png)

Hub thread: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000Cjk2&fId=0D51E00004kUxmB

I've read through the documentation, looked at the custom settings, but I'm stumped. This org is using the 1-to-1 Account Model, and it's my understanding that A4S is supposed to automatically detect that. This is a new error and we've been using A4S for years. Any help is much appreciated.

**Comment by davidhabib** [comment]
I've been able to figure out the problem.  occurs if you are not using the Household Account model.  The code is trying to validate security on npo02__Household__r.Name, and needs to treat this as npo02__Household__c.Name.  I'm working on a fix and will let you know when it is available.

**Comment by davidhabib** [comment]
Fixed in version 4.22 push upgraded on 4/11/2019.
